FONT = ("Helvetica", 14)

PRIMARY_BACKGROUND_COLOR = "#FFFFFF"
PRIMARY_BUTTON_BG_COLOR = "#72FFD4"
SECONDARY_BUTTON_BG_COLOR = "#3A6EA5"
SECONDARY_BUTTON_FG_COLOR = "#FFFFFF"

ACTIVE_CANVAS_BG_COLOR = "#EBEBEB"
PASSIVE_CANVAS_BG_COLOR = "#D0D0D0"

POINT_COLOR = "#000000"
TRIANGLE_COLOR = "#000000"

if __name__ == "__main__":
    print("This is package file\n")