BUTTON_WIDTH = 3
BUTTON_HEIGHT = 1

ACTIVE_OPERATOR_BTN_BG_COLOR = "#4F0D11"
ACTIVE_OPERATOR_BTN_FG_COLOR = "white"

INACTIVE_OPERATOR_BTN_BG_COLOR = "#D3471D"
INACTIVE_OPERATOR_BTN_FG_COLOR = "white"

MENU_BG_COLOR = "#EBEBDE"
MENU_FG_COLOR = "black"

EQUAL_BTN_BG_COLOR = "white"

ADD_WINDOW_BG_COLOR = "white"